baseURL = "https://bibiano.es/"
title = "Alex Bibiano Photography"
author = "Alex Bibiano"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
sitemap = true

[params]
  glass = "https://glass.photo/abibiano"
  instagram = "https://www.instagram.com/alexbibianophotography/"
  keywords = ["alex", "bibiano", "photography", "nature", "wildlife", "landscape", "macro", "nature photography", "wildlife photography", "landscape photography", "macro photography", "still life"]
  description = "Website dedicated to sharing and showcasing the photographic works created during the time devoted to my hobby, photography."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40
